# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://qaidjacobs.com
title: Qaid Jacobs Professional Portfolio
email: working.qaid@gmail.com
author: Qaid Jacobs
description: > # "Write an awesome description for your new site here.
  The work profile and experience of Qa'id Jacobs, a User Experience and Design Leader.
copyright: 'Copyright &copy; 2016 Qaid Jacobs. All Rights Reserved.'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/qaidj
  - title: github
    url: https://github.com/qaid
  - title: linkedin
    url: https://www.linkedin.com/in/qaidjacobs
  - title: medium
    url: https://medium.com/qa-id-jacobs
